

# This file was *autogenerated* from the file /Users/nnepal2/Documents/GitHub/ChowringofMatroids/FMSV/mainScripts/chowpoly_main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_20 = Integer(20)
import chowpoly_graphical.sage

def chow_data(edgelist, poly):
    serialized_matroid = {
        "name": list(edgelist),
        "chow_polynomial": str(poly)
    }
    return serialized_matroid

def write_to_json(chow_data):
    with open("chowpolys.json", "a") as f:
        json.dump(chow_data, f)
        f.write("\n")

def main():
    for i in range(_sage_const_3 , _sage_const_20 ):
        edgelist = graphs.CompleteGraph(i).edges(labels = False)
        result = chowpoly_graphical.chow_polynomial(edgelist)

if __name__ == "__main__":
    main()

